import type { Product } from "../types";
export declare const listProducts: () => Promise<{
    price: number;
    id: string;
    name: string;
    description: string;
    imageUrl: string;
    stock: number;
    category?: string | null;
    subcategory?: string | null;
    createdAt: string;
    updatedAt?: string;
}[]>;
export declare const getProduct: (id: string) => Promise<{
    price: number;
    id: string;
    name: string;
    description: string;
    imageUrl: string;
    stock: number;
    category?: string | null;
    subcategory?: string | null;
    createdAt: string;
    updatedAt?: string;
}>;
export declare const createProduct: (product: Partial<Product>) => Promise<{
    price: number;
    id: string;
    name: string;
    description: string;
    imageUrl: string;
    stock: number;
    category?: string | null;
    subcategory?: string | null;
    createdAt: string;
    updatedAt?: string;
}>;
export declare const updateProduct: (id: string, product: Partial<Product>) => Promise<{
    price: number;
    id: string;
    name: string;
    description: string;
    imageUrl: string;
    stock: number;
    category?: string | null;
    subcategory?: string | null;
    createdAt: string;
    updatedAt?: string;
}>;
export declare const deleteProduct: (id: string) => Promise<void>;
